apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apeiron
  namespace: infinity-horizons
spec:
  serviceName: apeiron-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apeiron
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apeiron
    spec:
      containers:
        - name: apeiron
          image: apeiron
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: apeiron
                  key: discord_token
