apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: apeiron
build:
  artifacts:
    - image: europe-west9-docker.pkg.dev/shikanime-studio-labs/apeiron
      buildpacks:
        builder: heroku/builder:24
      hooks:
        before:
          - command:
              - uv
              - export
              - --quiet
              - --format
              - requirements-txt
              - --output-file
              - requirements.txt
manifests:
  kustomize:
    paths:
      - manifests
deploy:
  cloudrun:
    projectid: shikanime-studio-labs
    region: europe-west9
