apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: apeiron
build:
  artifacts:
    - image: apeiron
      buildpacks:
        builder: heroku/builder:24
      hooks:
        before:
          - command:
              - uv
              - export
              - --quiet
              - --no-hashes
              - --format
              - requirements-txt
              - --output-file
              - requirements.txt
manifests:
  kustomize:
    paths:
      - manifests/base