apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: apeiron
  namespace: shikanime-studio-labs
build:
  artifacts:
    - image: europe-west9-docker.pkg.dev/shikanime-studio-labs/apeiron
      buildpacks:
        builder: heroku/builder:24
      hooks:
        before:
          - command:
              - uv
              - export
              - --quiet
              - --format
              - requirements-txt
              - --output-file
              - requirements.txt
  googleCloudBuild:
    bucket: shikanime-studio-labs-europe-west9-cloudbuild
manifests:
  kustomize:
    paths:
      - manifests
deploy:
  cloudrun:
    region: europe-west9
