apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: apeiron
build:
  artifacts:
    - image: apeiron
      buildpacks:
        builder: heroku/builder:24
      hooks:
        before:
          - command:
              - uv
              - export
              - --format
              - requirements-txt
              - --output-file
              - requirements.txt
