apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: apeiron
  namespace: shikanime-studio-labs
  labels:
    cloud.googleapis.com/location: europe-west9
spec:
  template:
    spec:
      containers:
        - name: apeiron
          image: europe-west9-docker.pkg.dev/shikanime-studio-labs/apeiron/run
          command:
            - uvicorn
          args:
            - apeiron.server:app
            - --host
            - 0.0.0.0
            - --port
            - $(PORT)
      serviceAccountName: apeiron-run@shikanime-studio-labs.iam.gserviceaccount.com
