apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: apeiron
  namespace: shikanime-studio-labs
  labels:
    cloud.googleapis.com/location: europe-west9
spec:
  template:
    spec:
      containers:
        - image: apeiron
      serviceAccountName: apeiron-run@shikanime-studio-labs.iam.gserviceaccount.com
