apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: mlflow
    newName: ghcr.io/mlflow/mlflow
    newTag: v2.0.1
resources:
  - ingress.yaml
  - svc.yaml
  - sts.yaml
  - pvc.yaml
labels:
  - pairs:
      app.kubernetes.io/name: mlflow
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: baguetto
      app.kubernetes.io/version: v2.0.1
