apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-runs-data
  namespace: infinity-horizons
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-artifacts-data
  namespace: infinity-horizons
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi