apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-runs-data
  namespace: infinity-horizons
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: nishir-standard
  volumeMode: Filesystem
  volumeName: mlflow-runs-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-artifacts-data
  namespace: infinity-horizons
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: nishir-standard
  volumeMode: Filesystem
  volumeName: mlflow-artifacts-data
