apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mlflow
  namespace: infinity-horizons
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mlflow
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mlflow
    spec:
      containers:
        - name: mlflow
          image: mlflow
          command:
            - mlflow
          args:
            - server
            - --host=0.0.0.0
            - --port=5000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mlflow
                  key: access_key_id
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: mlflow
                  key: region
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mlflow
                  key: secret_access_key
            - name: MLFLOW_ARTIFACTS_DESTINATION
              valueFrom:
                configMapKeyRef:
                  name: mlflow
                  key: artifacts_destination
            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: mlflow
                  key: s3_endpoint_url
          ports:
            - name: http
              containerPort: 5000
