apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mlflow
  namespace: infinity-horizons
spec:
  template:
    spec:
      containers:
        - name: mlflow
          image: mlflow
          env:
            - name: MLFLOW_BACKEND_STORE_URI
              value: sqlite:///data/mlflow.db
          volumeMounts:
            - name: data
              mountPath: /data
      securityContext:
        fsGroup: 1001
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mlflow-data
