apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: nishir-mlflow
spec:
  statefulSet:
    pod:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: mlflow
                topologyKey: kubernetes.io/hostname
