apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-data
  namespace: infinity-horizons
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: nishir-standard
  volumeMode: Filesystem
  volumeName: mlflow-data
